# 318320488 
# graffis
compile: bin find
	javac -cp biuoop-1.4.jar: @sources.txt -d bin

run:
	java -cp biuoop-1.4.jar:bin:resources Ass7Game
    
bin:
	mkdir bin

check:
	java -jar /u/stud/graffis/oop/checkstyle-5.7-all.jar -c /u/stud/graffis/oop/biuoop.xml src/*.java

jar:
	jar cfm ass7game.jar Manifest.mf -C bin . -C resources .

find:
	find src -name "*.java" >sources.txt
